class Target:
    name: str
    config_class: object
    config: dict[str, object]

    def __init__(
        self, *, config: dict[str, object] | None = ..., validate_config: bool = ...,
    ) -> None: ...
    @property
    def singer_catalog(self) -> dict[str, object]: ...
    def get_sink_class(self, stream_name: str) -> type[Sink]: ...
    def validate_config(self) -> None: ...
    def setup(self) -> None: ...
    def teardown(self) -> None: ...
    def cli(self) -> object: ...

class Sink:
    stream_name: str
    def __init__(
        self,
        target: Target,
        stream_name: str,
        schema: dict[str, object],
        key_properties: list[str],
    ) -> None: ...
    def process_batch(self, context: dict[str, object]) -> None: ...
    def process_record(
        self, record: dict[str, object], context: dict[str, object],
    ) -> None: ...
